/*
 * huellero.java
 *
 * Created on May 11, 2005, 10:51 AM
 */
package huellero;

import SecuGen.FDxSDKPro.jni.*;
import clases.cHuella;
import clases.conexionAPI;
import clases.hilo;
import clases.mAlumno;
import java.awt.*;
import java.awt.image.*;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class verificador extends javax.swing.JFrame {

    //Private instance variables
     public static long deviceName;
     public static long devicePort;
     public static JSGFPLib fplib = null;
     public static long ret;
     public static boolean bLEDOn;
    
     public static byte[] vrfMin = new byte[400];
    public static SGDeviceInfoParam deviceInfo = new SGDeviceInfoParam();
    public static BufferedImage imgVerification;
   
     public static boolean v1Captured = false;
     public static  int MINIMUM_QUALITY = 60;       //User defined
     public static  int MINIMUM_NUM_MINUTIAE = 20;  //User defined
     public static  int MAXIMUM_NFIQ = 2;
     public static cHuella cHuella = new cHuella();
     public static conexionAPI api = new conexionAPI();
    public static mAlumno alumno = null;
    public static Vector alumnos = null;
//User defined

    /**
     * Creates new form JSGD
     */
    public verificador() throws ClassNotFoundException, SQLException {
        traerAlumnos();
        bLEDOn = false;
        initComponents();
        disableControls();
        this.jComboBoxRegisterSecurityLevel.setSelectedIndex(4);
        this.jComboBoxVerifySecurityLevel.setSelectedIndex(4);
        this.setLocationRelativeTo(null);
        conectarHuellero();
        hilo h= new hilo();
        h.start();
    }

    private void disableControls() {

        this.jButtonCaptureV1.setEnabled(false);
       
        this.jButtonVerify.setEnabled(false);

        this.jButtonInit.setEnabled(true);
    }

    private void enableControls() {

        this.jButtonCaptureV1.setEnabled(true);

        this.jButtonInit.setEnabled(false);
    }

    private void enableRegisterAndVerifyControls() {
        
        if ( v1Captured) {
            this.jButtonVerify.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRegisterVerify = new javax.swing.JPanel();
        jLabelRegistration = new javax.swing.JLabel();
        jLabelVerification = new javax.swing.JLabel();
        jComboBoxRegisterSecurityLevel = new javax.swing.JComboBox();
        jComboBoxVerifySecurityLevel = new javax.swing.JComboBox();
        jLabelVerificationBox = new javax.swing.JLabel();
        jLabelVerifyImage = new javax.swing.JLabel();
        jButtonCaptureV1 = new javax.swing.JButton();
        jButtonVerify = new javax.swing.JButton();
        jProgressBarV1 = new javax.swing.JProgressBar();
        jButtonInit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSliderQuality = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSliderSeconds = new javax.swing.JSlider();
        jLabelSecurityLevel1 = new javax.swing.JLabel();
        jComboBoxDeviceName = new javax.swing.JComboBox();
        jLabelDeviceName = new javax.swing.JLabel();
        jLabelSpacer1 = new javax.swing.JLabel();
        jLabelSpacer2 = new javax.swing.JLabel();

        setTitle("Asistencia UNU");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStatus.setText("Click Initialize Button ...");
        jLabelStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 310, 30));

        jPanelRegisterVerify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistration.setText("Registracion");
        jPanelRegisterVerify.add(jLabelRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabelVerification.setText("Verificacion");
        jPanelRegisterVerify.add(jLabelVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jComboBoxRegisterSecurityLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOWEST", "LOWER", "LOW", "BELOW_NORMAL", "NORMAL", "ABOVE_NORMAL", "HIGH", "HIGHER", "HIGHEST" }));
        jPanelRegisterVerify.add(jComboBoxRegisterSecurityLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, -1));

        jComboBoxVerifySecurityLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOWEST", "LOWER", "LOW", "BELOW_NORMAL", "NORMAL", "ABOVE_NORMAL", "HIGH", "HIGHER", "HIGHEST" }));
        jComboBoxVerifySecurityLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVerifySecurityLevelActionPerformed(evt);
            }
        });
        jPanelRegisterVerify.add(jComboBoxVerifySecurityLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, -1));

        jLabelVerificationBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Verification"));
        jPanelRegisterVerify.add(jLabelVerificationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 190));

        jLabelVerifyImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabelVerifyImage.setMinimumSize(new java.awt.Dimension(130, 150));
        jLabelVerifyImage.setPreferredSize(new java.awt.Dimension(130, 150));
        jPanelRegisterVerify.add(jLabelVerifyImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jButtonCaptureV1.setText("Captura Verificar");
        jButtonCaptureV1.setActionCommand("jButton1");
        jButtonCaptureV1.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonCaptureV1.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonCaptureV1.setPreferredSize(new java.awt.Dimension(130, 30));
        jButtonCaptureV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaptureV1ActionPerformed(evt);
            }
        });
        jPanelRegisterVerify.add(jButtonCaptureV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jButtonVerify.setText("Verficar");
        jButtonVerify.setActionCommand("jButton1");
        jButtonVerify.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonVerify.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonVerify.setPreferredSize(new java.awt.Dimension(130, 30));
        jButtonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifyActionPerformed(evt);
            }
        });
        jPanelRegisterVerify.add(jButtonVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        jProgressBarV1.setForeground(new java.awt.Color(0, 51, 153));
        jPanelRegisterVerify.add(jProgressBarV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, -1));

        jButtonInit.setText("CONECTAR");
        jButtonInit.setMaximumSize(new java.awt.Dimension(100, 30));
        jButtonInit.setMinimumSize(new java.awt.Dimension(100, 30));
        jButtonInit.setName("jButtonInit"); // NOI18N
        jButtonInit.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInitActionPerformed(evt);
            }
        });
        jPanelRegisterVerify.add(jButtonInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 100, 30));

        jLabel2.setText("Image Quality");
        jPanelRegisterVerify.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jSliderQuality.setMajorTickSpacing(10);
        jSliderQuality.setMinorTickSpacing(5);
        jSliderQuality.setPaintLabels(true);
        jSliderQuality.setPaintTicks(true);
        jSliderQuality.setName(""); // NOI18N
        jSliderQuality.setOpaque(false);
        jPanelRegisterVerify.add(jSliderQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, -1));

        jLabel3.setText("Timeout (seconds)");
        jPanelRegisterVerify.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jSliderSeconds.setMajorTickSpacing(1);
        jSliderSeconds.setMaximum(10);
        jSliderSeconds.setMinimum(1);
        jSliderSeconds.setPaintLabels(true);
        jSliderSeconds.setPaintTicks(true);
        jSliderSeconds.setValue(5);
        jPanelRegisterVerify.add(jSliderSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, -1));

        jLabelSecurityLevel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel de Seguridad"));
        jPanelRegisterVerify.add(jLabelSecurityLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 130));

        jTabbedPane1.addTab("REGISTRAR Y VERIFICAR", jPanelRegisterVerify);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 460, 380));
        jTabbedPane1.getAccessibleContext().setAccessibleName("MARCADO DE ASISTENCIA");

        jComboBoxDeviceName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUTO", "HU20-AP", "HU20-A", "HU10-AP", "HU10", "HUPX", "HU20", "HSDU04P", "HSDU03P", "HFDU02" }));
        jComboBoxDeviceName.setMinimumSize(new java.awt.Dimension(350, 10));
        jComboBoxDeviceName.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jComboBoxDeviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, -1));

        jLabelDeviceName.setText("Modelo huellero");
        getContentPane().add(jLabelDeviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 110, -1));

        jLabelSpacer1.setText(" ");
        getContentPane().add(jLabelSpacer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 10, -1));

        jLabelSpacer2.setText(" ");
        getContentPane().add(jLabelSpacer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButtonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifyActionPerformed
        try {
            verificar();
        } catch (SQLException ex) {
            Logger.getLogger(verificador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonVerifyActionPerformed
public  static void leerHuella(){
    
          int[] quality = new int[1];
          int[] numOfMinutiae = new int[1];
        byte[] imageBuffer1 = ((java.awt.image.DataBufferByte) imgVerification.getRaster().getDataBuffer()).getData();
        long iError = SGFDxErrorCode.SGFDX_ERROR_NONE;
        iError = fplib.GetImageEx(imageBuffer1, jSliderSeconds.getValue() * 1000, 0, jSliderQuality.getValue());
        fplib.GetImageQuality(deviceInfo.imageWidth, deviceInfo.imageHeight, imageBuffer1, quality);
        jProgressBarV1.setValue(quality[0]);
        SGFingerInfo fingerInfo = new SGFingerInfo();
        fingerInfo.FingerNumber = SGFingerPosition.SG_FINGPOS_LI;
        fingerInfo.ImageQuality = quality[0];
        fingerInfo.ImpressionType = SGImpressionType.SG_IMPTYPE_LP;
        fingerInfo.ViewNumber = 1;

        if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
            jLabelVerifyImage.setIcon(new ImageIcon(imgVerification.getScaledInstance(130, 150, Image.SCALE_DEFAULT)));
            if (quality[0] < MINIMUM_QUALITY) {
                jLabelStatus.setText("GetImageEx() Success [" + ret + "] but image quality is [" + quality[0] + "]. Please try again");
            } else {
                jLabelStatus.setText("GetImageEx() Success [" + ret + "]");

                iError = fplib.CreateTemplate(fingerInfo, imageBuffer1, vrfMin);
                if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                    long nfiqvalue;
                    long ret2 = fplib.GetImageQuality(deviceInfo.imageWidth, deviceInfo.imageHeight, imageBuffer1, quality);
                    nfiqvalue = fplib.ComputeNFIQ(imageBuffer1, deviceInfo.imageWidth, deviceInfo.imageHeight);
                    ret2 = fplib.GetNumOfMinutiae(SGFDxTemplateFormat.TEMPLATE_FORMAT_SG400, vrfMin, numOfMinutiae);

                    if ((quality[0] >= MINIMUM_QUALITY) && (nfiqvalue <= MAXIMUM_NFIQ) && (numOfMinutiae[0] >= MINIMUM_NUM_MINUTIAE)) {
                        cHuella.crearImagen(imgVerification, vrfMin, 3);
                       jLabelStatus.setText("Verification Capture PASS QC. Quality[" + quality[0] + "] NFIQ[" + nfiqvalue + "] Minutiae[" + numOfMinutiae[0] + "]");
                        v1Captured = true;
                        try {
                            verificar();
                        } catch (SQLException ex) {
                            Logger.getLogger(verificador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                     

                    } else {
                       jLabelStatus.setText("Verification Capture FAIL QC. Quality[" + quality[0] + "] NFIQ[" + nfiqvalue + "] Minutiae[" + numOfMinutiae[0] + "]");
                       jButtonVerify.setEnabled(false);

                    }
                } else {
                   jLabelStatus.setText("CreateTemplate() Error : " + iError);
                }
            }
        } else {
           jLabelStatus.setText("GetImageEx() Error : " + iError);
        }
    
}
    private void jButtonCaptureV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaptureV1ActionPerformed

        int[] quality = new int[1];
        int[] numOfMinutiae = new int[1];
        byte[] imageBuffer1 = ((java.awt.image.DataBufferByte) imgVerification.getRaster().getDataBuffer()).getData();
        long iError = SGFDxErrorCode.SGFDX_ERROR_NONE;
        iError = fplib.GetImageEx(imageBuffer1, jSliderSeconds.getValue() * 1000, 0, jSliderQuality.getValue());
        fplib.GetImageQuality(deviceInfo.imageWidth, deviceInfo.imageHeight, imageBuffer1, quality);
        this.jProgressBarV1.setValue(quality[0]);
        SGFingerInfo fingerInfo = new SGFingerInfo();
        fingerInfo.FingerNumber = SGFingerPosition.SG_FINGPOS_LI;
        fingerInfo.ImageQuality = quality[0];
        fingerInfo.ImpressionType = SGImpressionType.SG_IMPTYPE_LP;
        fingerInfo.ViewNumber = 1;

        if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
            this.jLabelVerifyImage.setIcon(new ImageIcon(imgVerification.getScaledInstance(130, 150, Image.SCALE_DEFAULT)));
            if (quality[0] < MINIMUM_QUALITY) {
                this.jLabelStatus.setText("GetImageEx() Success [" + ret + "] but image quality is [" + quality[0] + "]. Please try again");
            } else {
                this.jLabelStatus.setText("GetImageEx() Success [" + ret + "]");

                iError = fplib.CreateTemplate(fingerInfo, imageBuffer1, vrfMin);
                if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                    long nfiqvalue;
                    long ret2 = fplib.GetImageQuality(deviceInfo.imageWidth, deviceInfo.imageHeight, imageBuffer1, quality);
                    nfiqvalue = fplib.ComputeNFIQ(imageBuffer1, deviceInfo.imageWidth, deviceInfo.imageHeight);
                    ret2 = fplib.GetNumOfMinutiae(SGFDxTemplateFormat.TEMPLATE_FORMAT_SG400, vrfMin, numOfMinutiae);

                    if ((quality[0] >= MINIMUM_QUALITY) && (nfiqvalue <= MAXIMUM_NFIQ) && (numOfMinutiae[0] >= MINIMUM_NUM_MINUTIAE)) {
                        cHuella.crearImagen(imgVerification, vrfMin, 3);
                        this.jLabelStatus.setText("Verification Capture PASS QC. Quality[" + quality[0] + "] NFIQ[" + nfiqvalue + "] Minutiae[" + numOfMinutiae[0] + "]");
                        v1Captured = true;
                        try {
                            verificar();
                        } catch (SQLException ex) {
                            Logger.getLogger(verificador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        this.enableRegisterAndVerifyControls();

                    } else {
                        this.jLabelStatus.setText("Verification Capture FAIL QC. Quality[" + quality[0] + "] NFIQ[" + nfiqvalue + "] Minutiae[" + numOfMinutiae[0] + "]");
                        this.jButtonVerify.setEnabled(false);

                    }
                } else {
                    this.jLabelStatus.setText("CreateTemplate() Error : " + iError);
                }
            }
        } else {
            this.jLabelStatus.setText("GetImageEx() Error : " + iError);
        }


    }//GEN-LAST:event_jButtonCaptureV1ActionPerformed
    public static void verificar() throws SQLException {
        long iError;
        long secuLevel = (long) (jComboBoxVerifySecurityLevel.getSelectedIndex() + 1);
        boolean[] matched = new boolean[1];
        matched[0] = false;
        byte[] bh1 = null;
        byte[] bh2 = null;
        //System.out.println(alumnos.size());
        for (int i = 0; i < alumnos.size(); i++) {
            mAlumno al = (mAlumno) alumnos.get(i);
            int ver = 0;
            try {
              System.out.println(al.getImghuella1());  
              
                ver = Integer.parseInt(al.getImghuella1().replace(" ", ""));
            } catch (Exception e) {
                ver = 0;
               
            }
            System.out.println(ver);
            if (ver == 0) {
                int myblobLength = (int) al.getBhuella1().length();
                bh1 = al.getBhuella1().getBytes(1, myblobLength);
                int myblobLength2 = (int) al.getBhuella2().length();
                bh2 = al.getBhuella2().getBytes(1, myblobLength2);
                iError = fplib.MatchTemplate(bh1, vrfMin, secuLevel, matched);
                System.out.println(bh1.toString());
                System.out.println(vrfMin.toString());
                System.out.println(bh2.toString());
                System.out.println(vrfMin.toString());
                if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                    if (matched[0]) {
                        jLabelStatus.setText("Verification Success (1st template)");
                        JOptionPane.showMessageDialog(null, "Hola "+al.getNombres());
                    } else {

                        iError = fplib.MatchTemplate(bh2, vrfMin, secuLevel, matched);
                        if (iError == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                            if (matched[0]) {
                                jLabelStatus.setText("Verification Success (2nd template)");
                                JOptionPane.showMessageDialog(null, "Hola "+al.getNombres());
                            } else {
                                jLabelStatus.setText("Verification Fail");
                            }
                        } else {
                            jLabelStatus.setText("Verification Attempt 2 Fail - MatchTemplate() Error : " + iError);
                        }

                    }
                } else {
                  jLabelStatus.setText("Verification Attempt 1 Fail - MatchTemplate() Error : " + iError);
                }

            } else {
                    System.out.println("Alumno sin huella registrada");
            }

        }
    }
    public void conectarHuellero(){
    int selectedDevice = jComboBoxDeviceName.getSelectedIndex();
        //AUTO
        //FDU08 Hamster Pro 20A
        //FDU07A Hamster Pro 10AP
        //FDU07 Hamster Pro 10
        //FDU06 Hamster Pro
        //FDU05 Hamster Pro 20
        //FDU04 Hamster IV
        //FDU03 Hamster Plus
        //FDU02 Hamster III
        switch (selectedDevice) {
            case 0: //USB
            default:
                this.deviceName = SGFDxDeviceName.SG_DEV_AUTO;
                break;
            case 1: //HU20-AP
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU08;
                break;
            case 2: //HU20-A
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU08;
                break;
            case 3: //HU10-AP
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU07A;
                break;
            case 4: //HU10
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU07;
                break;
            case 5: //HUPX
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU06;
                break;
            case 6: //HU20
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU05;
                break;
            case 7: //HSDU04P
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU04;
                break;
            case 8: //HSDU03P
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU03;
                break;
            case 9: //HFDU02
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU02;
                break;
        }
        if (fplib != null) {
            fplib.CloseDevice();
            fplib.Close();
            fplib = null;
        }
        fplib = new JSGFPLib();
        ret = fplib.Init(this.deviceName);
        if ((fplib != null) && (ret == SGFDxErrorCode.SGFDX_ERROR_NONE)) {
            this.jLabelStatus.setText("JSGFPLib Initialization Success");
            this.devicePort = SGPPPortAddr.AUTO_DETECT;

            boolean conetado = false;
            int puerto = 0;
            while (conetado == false) {
                this.devicePort = puerto;
                ret = fplib.OpenDevice(this.devicePort);
                if (ret == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                    conetado = true;
                    this.jLabelStatus.setText("OpenDevice() Success [" + ret + "]");
                    ret = fplib.GetDeviceInfo(deviceInfo);
                    if (ret == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                       
                        imgVerification = new BufferedImage(deviceInfo.imageWidth, deviceInfo.imageHeight, BufferedImage.TYPE_BYTE_GRAY);
                        this.enableControls();
                    } else {
                        this.jLabelStatus.setText("GetDeviceInfo() Error [" + ret + "]");

                    }
                } else {
                    this.jLabelStatus.setText("OpenDevice() Error [" + ret + "]");
                }
                puerto++;
            }
        } else {
            this.jLabelStatus.setText("JSGFPLib Initialization Failed");
        }
    }
    private void jButtonInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInitActionPerformed
        int selectedDevice = jComboBoxDeviceName.getSelectedIndex();
        //AUTO
        //FDU08 Hamster Pro 20A
        //FDU07A Hamster Pro 10AP
        //FDU07 Hamster Pro 10
        //FDU06 Hamster Pro
        //FDU05 Hamster Pro 20
        //FDU04 Hamster IV
        //FDU03 Hamster Plus
        //FDU02 Hamster III
        switch (selectedDevice) {
            case 0: //USB
            default:
                this.deviceName = SGFDxDeviceName.SG_DEV_AUTO;
                break;
            case 1: //HU20-AP
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU08;
                break;
            case 2: //HU20-A
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU08;
                break;
            case 3: //HU10-AP
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU07A;
                break;
            case 4: //HU10
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU07;
                break;
            case 5: //HUPX
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU06;
                break;
            case 6: //HU20
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU05;
                break;
            case 7: //HSDU04P
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU04;
                break;
            case 8: //HSDU03P
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU03;
                break;
            case 9: //HFDU02
                this.deviceName = SGFDxDeviceName.SG_DEV_FDU02;
                break;
        }
        if (fplib != null) {
            fplib.CloseDevice();
            fplib.Close();
            fplib = null;
        }
        fplib = new JSGFPLib();
        ret = fplib.Init(this.deviceName);
        if ((fplib != null) && (ret == SGFDxErrorCode.SGFDX_ERROR_NONE)) {
            this.jLabelStatus.setText("JSGFPLib Initialization Success");
            this.devicePort = SGPPPortAddr.AUTO_DETECT;

            boolean conetado = false;
            int puerto = 0;
            while (conetado == false) {
                this.devicePort = puerto;
                ret = fplib.OpenDevice(this.devicePort);
                if (ret == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                    conetado = true;
                    this.jLabelStatus.setText("OpenDevice() Success [" + ret + "]");
                    ret = fplib.GetDeviceInfo(deviceInfo);
                    if (ret == SGFDxErrorCode.SGFDX_ERROR_NONE) {
                       
                        imgVerification = new BufferedImage(deviceInfo.imageWidth, deviceInfo.imageHeight, BufferedImage.TYPE_BYTE_GRAY);
                        this.enableControls();
                    } else {
                        this.jLabelStatus.setText("GetDeviceInfo() Error [" + ret + "]");

                    }
                } else {
                    this.jLabelStatus.setText("OpenDevice() Error [" + ret + "]");
                }
                puerto++;
            }
        } else {
            this.jLabelStatus.setText("JSGFPLib Initialization Failed");
        }

    }//GEN-LAST:event_jButtonInitActionPerformed

    private void jComboBoxVerifySecurityLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVerifySecurityLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVerifySecurityLevelActionPerformed
    

    public void traerAlumnos() throws ClassNotFoundException, SQLException {
        alumnos = api.obtenertodos();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        new verificador().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonCaptureV1;
    private javax.swing.JButton jButtonInit;
    public static javax.swing.JButton jButtonVerify;
    private javax.swing.JComboBox jComboBoxDeviceName;
    public static javax.swing.JComboBox jComboBoxRegisterSecurityLevel;
    public static javax.swing.JComboBox jComboBoxVerifySecurityLevel;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDeviceName;
    private javax.swing.JLabel jLabelRegistration;
    private javax.swing.JLabel jLabelSecurityLevel1;
    private javax.swing.JLabel jLabelSpacer1;
    private javax.swing.JLabel jLabelSpacer2;
    public static javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelVerification;
    private javax.swing.JLabel jLabelVerificationBox;
    public static javax.swing.JLabel jLabelVerifyImage;
    private javax.swing.JPanel jPanelRegisterVerify;
    public static javax.swing.JProgressBar jProgressBarV1;
    public static javax.swing.JSlider jSliderQuality;
    public static javax.swing.JSlider jSliderSeconds;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
